// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBvEKjKPkv4X5m9IjooQ2vp5u32CPOBI',
    appId: '1:373495450223:web:ec7dce0276292e52cd9b9a',
    messagingSenderId: '373495450223',
    projectId: 'chat-app-75830',
    authDomain: 'chat-app-75830.firebaseapp.com',
    storageBucket: 'chat-app-75830.firebasestorage.app',
    measurementId: 'G-HTFH7HC55Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUsJYgIR4oX09fHFT5rktvO18LP__70OM',
    appId: '1:373495450223:android:6df28a365fecde7dcd9b9a',
    messagingSenderId: '373495450223',
    projectId: 'chat-app-75830',
    storageBucket: 'chat-app-75830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcvY6jllD-dpG9fWmdLnuZbNWEhY5Bcw',
    appId: '1:373495450223:ios:a3615d7c8db3a231cd9b9a',
    messagingSenderId: '373495450223',
    projectId: 'chat-app-75830',
    storageBucket: 'chat-app-75830.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcvY6jllD-dpG9fWmdLnuZbNWEhY5Bcw',
    appId: '1:373495450223:ios:a3615d7c8db3a231cd9b9a',
    messagingSenderId: '373495450223',
    projectId: 'chat-app-75830',
    storageBucket: 'chat-app-75830.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBvEKjKPkv4X5m9IjooQ2vp5u32CPOBI',
    appId: '1:373495450223:web:d59bc08ac870b550cd9b9a',
    messagingSenderId: '373495450223',
    projectId: 'chat-app-75830',
    authDomain: 'chat-app-75830.firebaseapp.com',
    storageBucket: 'chat-app-75830.firebasestorage.app',
    measurementId: 'G-EFRRGYG2P1',
  );

}